version: "3.9"
services:
  bot:
    environment:
      - LOG_LEVEL=debug
      - ACCRUE_REWARD=false
      - APP_ENV=docker-wrapped-standalone
    image: powerpool/power-agent-node:latest #eitelvolkerts/pagentv2:latest
    restart: always
    volumes:
      - ./config:/usr/app/config
      - ./keys:/usr/app/keys
